### ISSUE TITLE
URL set when clicking "Change Image"

### ISSUE THREAD

**Issue by timmyc** [xwp/wp-core-media-widgets#103]
When clicking "Change Image" for an existing image that is set via URL - the current image widget URL is set in the selection window.  Performing the same flow when changing an image from the media library, the current image is not selected:

__Change Image: Current Image set via URL__
<img width="1214" alt="customize__wordpress_develop_ _just_another_wordpress_site" src="https://cloud.githubusercontent.com/assets/22080/25408750/f555cb4a-29c3-11e7-9da8-36e071a47007.png">

__Change Image: Current Image from media library__
<img width="1221" alt="customize__wordpress_develop_ _just_another_wordpress_site" src="https://cloud.githubusercontent.com/assets/22080/25408807/204374b0-29c4-11e7-89a8-2ff2fc3aefed.png">

Note in the media library selection, the attachment details are shown in this selection view too, and they probably should not.

While not a blocker, if one is trying to change images via URL you have to select all/remove the existing URL to enter a new one.

**Comment by westonruter** [comment]
I don't think I understand. Could you create a video that demonstrates it? If you change image and provide the URL to an image that is also in the media library, the fact that it is already attachment should be irrelevant and it would be treated like an external image.

**Comment by timmyc** [comment]
![change-image](https://cloud.githubusercontent.com/assets/22080/25440425/44c8be7c-2a54-11e7-9b47-351f1fb76432.gif)

So I guess my question here is, when a user is 'Changing' the media, shouldn't the modal be opened up with an empty context as in no selection or metadata displayed?  Right now the modal is opened with the data for the current attachment whereas it kind of seems like we should open it in the default selection/empty state.

**Comment by obenland** [comment]
Yeah, I agree. It also shows the embed screen rather than defaulting to the media library

**Comment by westonruter** [comment]
> Yeah, I agree. It also shows the embed screen rather than defaulting to the media library

This was intentional actually. The idea was that if you supplied an external URL then if you wanted to tweak the URL, for example change the query params or fix a typo you made, you could do so by modifying the URL that is re-populated into that field. Maybe this isn't a common-enough use case to warrant this.

**Comment by obenland** [comment]
Oh, that didn't occur to me. Yeah, I think I'd probably expect that under "Edit" more than "Change"?

**Comment by westonruter** [comment]
The problem is that there is no such URL field in the image-details frame. 

The other consideration is when the user enters a different URL, would they want all of the other properties to be reset? This is particularly the case for an external URL, where the props (e.g. alt and caption) do not exist in the media library. It's very like that if they are changing the external URL that they don't want to change the alt and caption that they already provided. Having them get reset every time another external URL is provided I envision could be extremely frustrating.

**Comment by obenland** [comment]
I wonder if moving the focus from "Select File" to "Insert from URL" would be all it takes to make it not feel so jarring.

![screen shot 2017-04-26 at 2 33 55 pm](https://cloud.githubusercontent.com/assets/1398304/25458133/92de5e62-2a8d-11e7-8c0a-11dc4c5151d3.png)

**Comment by obenland** [comment]
Although it's still duplicating the editing experience to a degree

**Comment by westonruter** [comment]
It is duplicating in the negative sense, but it is re-using a familiar interface in a positive sense. That's partially why the attachment display settings weren't hidden, allowing the user to quickly set some of the most commonly-used settings (e.g. size and link URL) without having to open a second screen.

**Comment by melchoyce** [comment]
Was hard to wrap my brain around this one. After playing around with it, I think...

> I wonder if moving the focus from "Select File" to "Insert from URL" would be all it takes to make it not feel so jarring.

^ This is the way to go. 

Since my first instinct is, if you want to swap images and you inserted from a URL in the first place, the image you want to swap it out for is also coming from an external URL. It makes sense to return to the URL screen to change. However, having "Select image" focused creates some weird cognitive dissonance.

If this ends up feeling weird in practice, we can always change it later.

**Comment by westonruter** [comment]
I'll open a PR to fix the focus.
