### ISSUE TITLE
Button text can go over the button

### ISSUE THREAD

**Issue by samikeijonen** [xwp/wp-core-media-widgets#15]
In different languages words can be longer. In Finnish button text go over the button.

<img width="263" alt="text on button" src="https://cloud.githubusercontent.com/assets/1820415/23824785/a10f759c-0685-11e7-8616-9a622b546105.png">

**Comment by westonruter** [comment]
I used flexbox to try to make the two buttons equal width. I'm not a flexbox expert, but we could use `flex-grow` to allow the buttons to fully take up the width, but resize themselves when one of the buttons has more text. So in this example the left button maybe could be wider than the right button. Otherwise, an ellipsis could be used. Or in such languages that have longer strings the translation may need to just be “Change” as opposed to “Change media”.
