### ISSUE TITLE
Apply clearfix for all themes

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#34]
For the issue identified in https://github.com/xwp/wp-core-media-widgets/issues/13#issuecomment-287405452 for Twenty Sixteen and fixed in #30 with regards to `alignleft` and `alignright` causing images widgets to corrupt layouts of sidebars, I think that the clearfix fix should probably be applied by the image widget itself for all themes. I imagine there are many themes that don't anticipate widgets to be floating their contents in this way and so not implement clearfix.

**Comment by westonruter** [comment]
Thoughts on this one? I'm afraid of users messing up floating in their sidebars when they use alignment.

**Comment by joyously** [comment]
It is part of the Theme Unit Test data to check that themes clear floats properly. I think that mostly refers to the content area, but it should apply to widget areas also.  
Theme Unit Test data is standard for Theme Review.

**Comment by joyously** [comment]
Why would a user put alignleft or alignright if they didn't want it to affect what came after? Adding clearfix would defeat the whole purpose of alignment.

**Comment by westonruter** [comment]
The clearfix would be on the `.widget` container element, not the `img` itself.

**Comment by joyously** [comment]
And if it's inline style, it's difficult for themes to override. 
I've been telling theme authors to put widget areas in their "home page does everything" type of layouts, so the user can arrange the sections are they prefer, instead of the theme trying to present content in sections requiring content to be stored in theme options. So making it difficult for themes to control the floating of widgets defeats the purpose of having the theme be in charge of presentation.
The default alignment should be "none", not "left". If there are themes that break layout, then that theme should not have passed review, and should be fixed.

**Comment by westonruter** [comment]
> The default alignment should be "none", not "left". If there are themes that break layout, then that theme should not have passed review, and should be fixed.

The default `align` is indeed `none`: https://github.com/xwp/wp-core-media-widgets/blob/38664a52f48350f0947ade7560e16846692c5ec6/wp-includes/widgets/class-wp-widget-image.php#L77

So I guess we should leave this alone and if it becomes a problem it can be in the domain of themers fixing their styles, which apparently should already be accounting for floated content inside of widgets.
