### ISSUE TITLE
Default image size to "medium"

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#55]
Seems like it could be a better default size than full for the majority of themes.

**Comment by westonruter** [comment]
Especially when widgets are normally in a narrower sidebar context. If the widget has larger dimensions, the user can always switch the size to full. But in the case of defaulting to full, a user would likely very often accidentally embed huge images in a sidebar and not realize it because it would get sized down to fit via `max-width:100%`.
