### ISSUE TITLE
JS coding standards

### ISSUE THREAD

**Issue by afercia** [xwp/wp-core-media-widgets#80]
I'd recommend a general review before merging in core.

Minor things like spaces around arguments have patterns to follow clearly explained here:
https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#arrays-and-function-calls

Ideally, all these things (and more) should be addressed to avoid introducing even more inconsistencies in core.

Documentation:
https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/javascript/

While not explicitly mentioned, for analogy with PHP standards there should be a proper alignment, for example for the @param type, name, and description. Example from the current code:
```
* @param {wp.media.view.MediaFrame.Select} mediaFrame Select frame.
* @param {object} attachment Attachment object.
```

should be
```
* @param {wp.media.view.MediaFrame.Select} mediaFrame Select frame.
* @param {object}                          attachment Attachment object.
```

I'd also argue that `wp.media.view.MediaFrame.Select` is not a JS type :) I know this is common practice but IMHO should indicate just the proper JS type and `wp.media.view.MediaFrame.Select` should go in the description.

One more example:
```
* @param {Object}         options - Options.
* @param {Backbone.Model} options.model - Model.
* @param {jQuery}         options.el - Control container element.
```

here the alignment is a bit better, I wouldn't know what the `-` hyphen represents, and descriptions should be aligned. Same consideration for the type.

One more example, here the alignment looks good but I wouldn't know what the square brackets around param names are:
```
 * @param {string|Object} key       Attribute name or attribute pairs.
 * @param {mixed|Object}  [val]     Attribute value or options object.
 * @param {Object}        [options] Options when attribute name and value are passed separately.
```

**Comment by westonruter** [comment]
> Ideally, all these things (and more) should be addressed to avoid introducing even more inconsistencies in core.

@afercia Do you have examples of where these aren't being followed in the plugin? We have JSCS and ESLint checking the files for adherence to as many of these conventions as possible.

> While not explicitly mentioned, for analogy with PHP standards there should be a proper alignment

I suppose, if we must.

> I'd also argue that wp.media.view.MediaFrame.Select is not a JS type :) I know this is common practice but IMHO should indicate just the proper JS type and wp.media.view.MediaFrame.Select should go in the description.

I disagree. It is better to use the JS class in this case because it allows for editors to provide hinting and better static analysis. Using custom object types are correct per http://usejsdoc.org/tags-type.html

In the same way, we wouldn't want to use `object ` in PHP instead of `WP_Error`, right? 

> here the alignment is a bit better, I wouldn't know what the - hyphen represents, and descriptions should be aligned. Same consideration for the type.

Hyphens are allowed in JSDoc to separate the param identifier from the param description. This is to improve readability. I suspect this is in JSDoc and not PHPDoc because in PHP the param variables get prefixed with `$` so it is easier to see where the description starts. See http://usejsdoc.org/tags-param.html#examples

> One more example, here the alignment looks good but I wouldn't know what the square brackets around param names are:

Per jsdoc, brackets indicate the parameter is optional. See: http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values

**Comment by afercia** [comment]
> Do you have examples of where these aren't being followed in the plugin? 

See the link I've posted above:
https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#arrays-and-function-calls

so, for example:

`ImageWidgetModel = component.MediaWidgetModel.extend( {} );`

those spaces shouldn't be there and aren't used in core.

same in similar cases 
> // Function with a callback, object, or array as the sole argument:
> // No space on either side of the argument

so for example: 
```js
control.model.set( {
	attachment_id: imageData.attachment_id,
	alt: imageData.alt,
	caption: imageData.caption,
	image_classes: imageData.extraClasses,
	image_title: imageData.title,
	link_classes: imageData.linkClassName,
	link_rel: imageData.linkRel,
	link_target_blank: imageData.linkTargetBlank,
	link_type: imageData.link,
	link_url: imageData.linkUrl,
	size: imageData.size,
	url: imageData.url,
	width: 'custom' === imageData.size ? imageData.customWidth : imageData.width,
	height: 'custom' === imageData.size ? imageData.customHeight : imageData.height
} );
```

it's a function with an object as sole argument, shouldn't have spaces. 

> // Function with a callback, object, or array as the last argument:
> // No space after after the last argument

so for example
```js
				_.extend( props, {
					attachment_id: attachment.id,
					alt: attachment.alt,
					caption: attachment.caption,
					image_classes: '',
					image_title: '',
					link_classes: '',
					link_rel: '',
					link_url: displaySettings.linkUrl,
					link_target_blank: false,
					link_type: displaySettings.link,
					size: displaySettings.size,
					url: attachment.sizes[ displaySettings.size ].url,
					width: 0, // Reset.
					height: 0 // Reset.
				} );
```

shouldn't have spaces. etc. etc.

> We have JSCS and ESLint checking the files 

Apparently they're missing to catch some cases. If ESLint is using the default conf, well it doesn't match the WP standards.

> In the same way, we wouldn't want to use object in PHP instead of WP_Error, right?

If it was up to me, I'd do that also for PHP 🙂  I agree it's better for editors, not so good for beginners and for educational purposes though.

> Hyphens are allowed in JSDoc 

But not used in core, so I don't fully understand the argument. Also, they're used only in a few cases in the files in this plugin, so it looks like an inconsistency to me.

> Per jsdoc, brackets indicate the parameter is optional.

But brackets are not used in core, so I don't fully understand the argument. In the WP docs standrds https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/javascript/ there's a clear example of how optional params should be documented:

`* @param type $var Optional. Description.`

**Comment by westonruter** [comment]
> But not used in core, so I don't fully understand the argument. Also, they're used only in a few cases in the files in this plugin, so it looks like an inconsistency to me.

I don't feel strongly about using the hyphens or not, but jsdoc indicates they can be used for improving readability. And they are used in core, at least in:
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/js/customize-controls.js
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/js/customize-base.js
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/js/customize-selective-refresh.js
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/js/customize-preview.js

> If it was up to me, I'd do that also for PHP 🙂 I agree it's better for editors, not so good for beginners and for educational purposes though.

I'd say it is _better_ for beginners and for educational purposes since it is explicit what the kind of object is. IDEs are able to flag incorrect usage via static analysis when the type is explicit. Anyway, using explicit types is common throughout JS and PHP, so it's here to stay.

> But brackets are not used in core, so I don't fully understand the argument.

Actually they _are_ very much used in core. See:
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/js/customize-controls.js
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/js/media-views.js
* https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/js/media-models.js

Editors like WebStorm understand the jsdoc bracket syntax and will not flag calling functions that omit those parameters. It is phpdoc that is deficient for not supporting an explicit syntax for marking parameters as optional.

**Comment by afercia** [comment]
Thanks @westonruter !
For the records, I absolutely think the WP JS coding standards could be discussed and maybe updated a bit. Something for WordCamp Europe maybe? 

One thing that bothers me a bit is having to mentally switch to one standard to a different one when switching projects 🙂  
On the other hand, anything that avoids one more key press without compromising code readability is a big plus for me, so some ESLint defaults (e.g. if I'm not wrong double quotes) are a no-no for me.
