### ISSUE TITLE
Improve rendering of video poster images

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#95]
Improve rendering of `poster` images when ME.js will show YouTube or Vimeo players with their own poster frames underneath.

**Comment by westonruter** [comment]
For Vimeo and YouTube embeds, perhaps we should just skip passing the `poster` to the video shortcode since the players will handle the poster themselves. That is, if the `poster` for the image is set as coming from Vimeo or YouTube. If the user selects a custom poster, however, the problem remains as it should still be shown. In that case, it seems that `background-size:cover` may be a better approach than the default `background-size:contain`.

**Comment by westonruter** [comment]
We should also reset the `poster` image if a video is for Vimeo or YouTube and the user switches from an external oEmbed over to a hosted video file in the media library.

**Comment by melchoyce** [comment]
Is it possible to get a rundown of all the possible scenarios here? ex:

1. Embed a YouTube video; YouTube supplies poster image
2. Embed a Vimeo video; Vimeo supplies poster image
3. Upload a video; ???

**Comment by westonruter** [comment]
I think the scenarios are:

1. Embed a YouTube/Vimeo video using the service's poster image (as player would do by default)
2. Embed a YouTube/Vimeo video with a custom poster image (perhaps this should be disallowed)
3. Embed a video from media library with a poster image from media library
4. Embed a video from media library without a poster image

**Comment by melchoyce** [comment]
What determines whether an uploaded video has a poster image?

**Comment by westonruter** [comment]
A user has to manually select a poster for uploaded videos. For external YouTube/Vimeo videos, a poster is available to us via oEmbed.

**Comment by melchoyce** [comment]
I was confused about how you could select a poster image, since there isn't an option to add one when you upload a video, or from the media library (that I can see), but I've finally figured it out: 

![screen shot 2017-04-26 at 7 06 08 pm](https://cloud.githubusercontent.com/assets/2846578/25460873/d0c22ac6-2ab3-11e7-910f-26279ed86854.png)
![screen shot 2017-04-26 at 7 06 12 pm](https://cloud.githubusercontent.com/assets/2846578/25460874/d2088006-2ab3-11e7-9e75-8bf4a896ecd6.png)
![screen shot 2017-04-26 at 7 06 15 pm](https://cloud.githubusercontent.com/assets/2846578/25460875/d33fed92-2ab3-11e7-8e9e-2fa4544ece34.png)

You can only add it when you're _editing_ a video you've embedded into something. Not the most intuitive UI. 😬 

Now that I have a better idea of how this works, I think we shouldn't let people add poster images in WordPress to YouTube or Vimeo videos, since you can control that on those services themselves. 

The place where I'm confused is, every video I've uploaded to WordPress has some sort of image preview. Is there a particular format that doesn't allow this, or shows a blank preview? Or is that separate from poster images, which override that preview? Do we even need poster images in a v1 video widget?

**Comment by westonruter** [comment]
The videos I upload don't have a thumbnail preview. I just see the generic icon.

**Comment by westonruter** [comment]
This is what I see:

![image](https://cloud.githubusercontent.com/assets/134745/25485422/e4cc9a06-2b2b-11e7-9510-dedc0e45c68a.png)

**Comment by melchoyce** [comment]
I see that too:

<img width="1189" alt="screen shot 2017-04-27 at 10 58 58 am" src="https://cloud.githubusercontent.com/assets/2846578/25489690/9d6c293a-2b38-11e7-93b3-5272668252d9.png">

But when I add it to the widget, I have a preview:

<img width="288" alt="screen shot 2017-04-27 at 10 59 11 am" src="https://cloud.githubusercontent.com/assets/2846578/25489696/a2fea8e6-2b38-11e7-8d4c-ed73c46d7f67.png">

**Comment by westonruter** [comment]
The image you see here is just the first frame of the video because by default the video template there renders with `preload="metadata"`. So it's not actually a separate poster frame image. You can see this in the customizer preview window as well, if you change the preload option to “None” in the Edit Video frame:

![image](https://cloud.githubusercontent.com/assets/134745/25497359/4c48aee2-2b52-11e7-88b8-8a78cb1f5d4b.png)

![image](https://cloud.githubusercontent.com/assets/134745/25497345/3fd6a9d4-2b52-11e7-9602-02fd1124d5de.png)

**Comment by melchoyce** [comment]
Can we exclude poster images from the v1 of the widget entirely, and always show the first frame of the video by default?

**Comment by westonruter** [comment]
Yes, it can be removed for v1 if need be.

**Comment by melchoyce** [comment]
Cool, let's remove it for the initial release 👍
